obj-$(CONFIG_L2LV_VBD) += vbd_client.o vbd_debug.o
obj-$(CONFIG_L2LV_SERVER) += vbd_interface.o

obj-$(CONFIG_L2LV_VBD_SERVER) += vbd_server.o vbd_shlogic.o
vbd_shlogic-y += vbd_link.o vbd_joblist.o

