/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /data/jenkins/workspace/alex-platform_CI_master/build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.22.0.real ../bin/enc2xs -Q -o eu_01_t.c -f eu_01_t.fnm
 enc2xs VERSION 2.17
*/
extern encode_t euc_jp_encoding;
