#
# arch/p4/init/Makefile
#
# Copyright (c) 2013, David Engraf, Sysgo AG <david dot engraf at sysgo dot com>
#

obj-y := version.o

# use PikeOS includes and flags
EXTRA_CFLAGS += $(PIKEOS_INCLUDE) $(PIKEOS_CFLAGS)
